// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXxzA4so93oJ6dv-MlrhebkYbBQcl47CI',
    appId: '1:738991844728:web:5fd7297d2b3aa30646ec8d',
    messagingSenderId: '738991844728',
    projectId: 'colorful-note',
    authDomain: 'colorful-note.firebaseapp.com',
    storageBucket: 'colorful-note.appspot.com',
    measurementId: 'G-VRQ1MVX2KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKbhrJHtRAOzQNnqZe3PMohDSnfPvjiSY',
    appId: '1:738991844728:android:9a3ef0e356ccd30c46ec8d',
    messagingSenderId: '738991844728',
    projectId: 'colorful-note',
    storageBucket: 'colorful-note.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUxZM5AzhDH5BYf0fksPgoysufeiXfq_c',
    appId: '1:738991844728:ios:1aacbe2d9a2a35fc46ec8d',
    messagingSenderId: '738991844728',
    projectId: 'colorful-note',
    storageBucket: 'colorful-note.appspot.com',
    iosBundleId: 'com.example.colorfulNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUxZM5AzhDH5BYf0fksPgoysufeiXfq_c',
    appId: '1:738991844728:ios:0d62ee601a93e69c46ec8d',
    messagingSenderId: '738991844728',
    projectId: 'colorful-note',
    storageBucket: 'colorful-note.appspot.com',
    iosBundleId: 'com.example.colorfulNotesApp.RunnerTests',
  );
}
